name: dev-pr
on:
  schedule:
    - cron: '10 * * * *'
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "dev"
        destination_branch: "master"        
        github_token: ${{ secrets.PAT }}
