name: pull-request

on:
  schedule:
    - cron: '20 * * * *'
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "beo"
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
