name: pull-request
on:
  schedule:
    - cron: '15 * * * *'
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "beo"
        destination_branch: "master"
        token: ${{ secrets.PAT }} 
        #github_token: ${{ secrets.GITHUB_TOKEN }}
